import os

base_dir = os.path.abspath(os.path.dirname(__file__))
SAMPLE_LENGTH=32

# TRAINING
MAX_EPOCHS=10
NUM_STEPS=16
BATCH_SIZE=32
KEEP_PROB=0.5
HIDDEN_SIZE=512
NUM_POEMS= -1 #1024
INIT_SCALE = 0.05
LEARNING_RATE = 0.003

# DEVELOPMENT TESTING:
# MAX_EPOCHS=2
# NUM_STEPS=2
# BATCH_SIZE=2
# KEEP_PROB=0.5
# HIDDEN_SIZE=16
# NUM_POEMS=32