import os

base_dir = os.path.abspath(os.path.dirname(__file__))
SAMPLE_LENGTH=32

# TRAINING
MAX_EPOCHS=10
NUM_STEPS=16
BATCH_SIZE=16
KEEP_PROB=0.5
HIDDEN_SIZE=256
NUM_POEMS=1024

# DEVELOPMENT TESTING:
# MAX_EPOCHS=2
# NUM_STEPS=2
# BATCH_SIZE=2
# KEEP_PROB=0.5
# HIDDEN_SIZE=16
# NUM_POEMS=32